package com.deepblue.design_pattern_inaction.designpatterns_003_behavior.designpatterns_011_template_method.service.prop.dice;


import com.deepblue.design_pattern_inaction.designpatterns_003_behavior.designpatterns_011_template_method.service.prop.common.PropCommonService;

public interface DicePropService extends PropCommonService {
}
