package com.deepblue.design_pattern_inaction.designpatterns_003_behavior.designpatterns_011_template_method.service.game.common;


import com.deepblue.design_pattern_inaction.designpatterns_003_behavior.designpatterns_011_template_method.service.common.PropGameService;

public interface GameCommonService extends PropGameService {

}
